/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import java.awt.Color;
import java.util.Set;

/**
 *
 * @author cerva
 */
public class MenuP extends javax.swing.JFrame {

    /**
     * Creates new form MenuP
     */
    public MenuP() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    int mousex;
    int mousey;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelP = new javax.swing.JPanel();
        rrButton = new javax.swing.JPanel();
        rrLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        fcsfsButton = new javax.swing.JPanel();
        fcfsLabel = new javax.swing.JLabel();
        sjfButton = new javax.swing.JPanel();
        sjfLabel = new javax.swing.JLabel();
        mover = new javax.swing.JPanel();
        exitP = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);

        PanelP.setBackground(new java.awt.Color(255, 255, 255));
        PanelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rrButtonMouseClicked(evt);
            }
        });

        rrLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rrLabel.setText("RR");

        javax.swing.GroupLayout rrButtonLayout = new javax.swing.GroupLayout(rrButton);
        rrButton.setLayout(rrButtonLayout);
        rrButtonLayout.setHorizontalGroup(
            rrButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rrButtonLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(rrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        rrButtonLayout.setVerticalGroup(
            rrButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rrButtonLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(rrLabel)
                .addContainerGap())
        );

        PanelP.add(rrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, -1));

        TitleLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        TitleLabel.setText("MENU LOS SISTEMAS DE PLANEACION");
        PanelP.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        fcsfsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fcsfsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fcsfsButtonMouseClicked(evt);
            }
        });

        fcfsLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        fcfsLabel.setText("FCFS");

        javax.swing.GroupLayout fcsfsButtonLayout = new javax.swing.GroupLayout(fcsfsButton);
        fcsfsButton.setLayout(fcsfsButtonLayout);
        fcsfsButtonLayout.setHorizontalGroup(
            fcsfsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fcsfsButtonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(fcfsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        fcsfsButtonLayout.setVerticalGroup(
            fcsfsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fcsfsButtonLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(fcfsLabel)
                .addContainerGap())
        );

        PanelP.add(fcsfsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, -1));

        sjfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sjfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sjfButtonMouseClicked(evt);
            }
        });

        sjfLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        sjfLabel.setText("SJF");

        javax.swing.GroupLayout sjfButtonLayout = new javax.swing.GroupLayout(sjfButton);
        sjfButton.setLayout(sjfButtonLayout);
        sjfButtonLayout.setHorizontalGroup(
            sjfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sjfButtonLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(sjfLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        sjfButtonLayout.setVerticalGroup(
            sjfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sjfButtonLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(sjfLabel)
                .addContainerGap())
        );

        PanelP.add(sjfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));

        mover.setBackground(new java.awt.Color(255, 255, 255));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });

        javax.swing.GroupLayout moverLayout = new javax.swing.GroupLayout(mover);
        mover.setLayout(moverLayout);
        moverLayout.setHorizontalGroup(
            moverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        moverLayout.setVerticalGroup(
            moverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        PanelP.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 430, -1));

        exitP.setBackground(new java.awt.Color(255, 255, 255));
        exitP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPMouseExited(evt);
            }
        });

        exitText.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("X");

        javax.swing.GroupLayout exitPLayout = new javax.swing.GroupLayout(exitP);
        exitP.setLayout(exitPLayout);
        exitPLayout.setHorizontalGroup(
            exitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitText)
                .addContainerGap())
        );
        exitPLayout.setVerticalGroup(
            exitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(exitText))
        );

        PanelP.add(exitP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelP, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y -mousey);
    }//GEN-LAST:event_moverMouseDragged

    
    
    
    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked

    }//GEN-LAST:event_moverMouseClicked

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed

        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void exitPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitPMouseClicked

    private void exitPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseEntered
        exitP.setBackground(Color.red);
    }//GEN-LAST:event_exitPMouseEntered

    private void exitPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseExited
        exitP.setBackground(Color.white);
    }//GEN-LAST:event_exitPMouseExited

    private void fcsfsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcsfsButtonMouseClicked
        fcfsForm ventana = new fcfsForm();
        ventana.setVisible(true);
        dispose();

    }//GEN-LAST:event_fcsfsButtonMouseClicked

    private void sjfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfButtonMouseClicked
        SjfForm ventana = new SjfForm();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_sjfButtonMouseClicked

    private void rrButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rrButtonMouseClicked
        RRForm ventana = new RRForm();
        ventana.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_rrButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuP().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelP;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel exitP;
    private javax.swing.JLabel exitText;
    private javax.swing.JLabel fcfsLabel;
    private javax.swing.JPanel fcsfsButton;
    private javax.swing.JPanel mover;
    private javax.swing.JPanel rrButton;
    private javax.swing.JLabel rrLabel;
    private javax.swing.JPanel sjfButton;
    private javax.swing.JLabel sjfLabel;
    // End of variables declaration//GEN-END:variables
}
